# Site settings
title: EthioNLP's NLP
email:
description: Ethiopia is a country with multinational and multilingual that support more that 83 different languages. All the languages are underrepresented. We are here to provide different NLP application for the Ethiopian languages. Let's know your NLP problem to solve as per your requirement.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

twitter_username:
github_username:

# Build settings
markdown: kramdown

sass:
    sass_dir: styles/_sass
    style: compressed
